fun main() {
    val originator = Originator()
    val careTaker = CareTaker()
    val textRedactor = TextRedactor()
    textRedactor.changeText("State #1")
    originator.setState(textRedactor.getText())
    textRedactor.changeText("State #2")
    originator.setState(textRedactor.getText())
    careTaker.add(originator.saveStateToMemento())
    textRedactor.changeText("State #3")
    originator.setState(textRedactor.getText())
    careTaker.add(originator. saveStateToMemento())
    textRedactor.changeText("State #4")
    originator.setState(textRedactor.getText())
    println("Current State: " + originator.getState())
    originator.getStateFromMemento(careTaker.get(0))
    println("First saved State: " + originator.getState())
    originator.getStateFromMemento(careTaker.get(1))
    println("Second saved State: " + originator.getState())
}